// The globals that `term boot` prepends, installed by hand.
//
//   import './shim'          FIRST, before any import of ../host/**
//
// A module under ../host/ is emitted assuming the natives it calls are
// already global: `octets`, `cipher`, `bit`, `digest` and a `require`. Under
// `term boot` they are prepended to the bundle. Reaching the same module
// directly from tsx skips that step, and the first native call fails with
// `ReferenceError: octets is not defined` pointing at emitted code rather
// than at the missing setup.
//
// Imported for the side effect. It exports nothing on purpose.
import { createRequire } from 'node:module'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const require_ = createRequire(import.meta.url)

// esbuild comes from the Term toolchain these tests already run on. Zone has no
// install of its own: it left the Term tree on 2026-10-02, and inside it this
// resolved through the Term package's node_modules.
const { transformSync } = createRequire(
  resolve(HERE, '../../term/deck/term/package.json'),
)('esbuild') as {
  transformSync: (source: string, options: object) => { code: string }
}

;(globalThis as any).require = require_

for (const [file, name] of Object.entries({
  bytes: 'octets',
  cipher: 'cipher',
  bit: 'bit',
  digest: 'digest',
})) {
  let src: string

  try {
    src = readFileSync(
      resolve(HERE, `../../term/deck/term/deck/base/code/native/node/runtime/${file}.ts`),
      'utf8',
    )
  } catch {
    continue
  }

  const js = transformSync(src, { loader: 'ts', format: 'cjs' }).code

  ;(globalThis as any)[name] = new Function(
    'require',
    `${js}; return ${file}`,
  )(require_)
}

// Zone's OWN runtime shims, which live beside the module that docks each one
// rather than in the stdlib. `nativePrelude` finds them by walking up from
// the docking module; here they are named directly.
//
//   mill    the compiler's parser, generated by `pnpm run make:read`
//   vault   the Bitwarden SDK
//
// Without these, a test that reaches ../host/** directly dies with
// `ReferenceError: mill is not defined` inside emitted code.
for (const [where, name] of Object.entries({
  'code/tool/runtime/mill.ts': 'mill',
  'code/hold/runtime/vault.ts': 'vault',
})) {
  let src: string

  try {
    src = readFileSync(resolve(HERE, '..', where), 'utf8')
  } catch {
    continue
  }

  const js = transformSync(src, { loader: 'ts', format: 'cjs' }).code

  ;(globalThis as any)[name] = new Function(
    'require',
    `${js}; return ${name}`,
  )(require_)
}

Object.defineProperty(globalThis, 'crypto', {
  value: require_('node:crypto'),
  configurable: true,
  writable: true,
})
