// GENERATED by `pnpm run make:read` in @term/deck. Do not edit.
//
// Reading a `.tree` file THROUGH THE COMPILER, never by hand.
//
// Every custom `.tree` dialect is parsed by the Term compiler into a CST and
// an AST, and integrated by defining a mill. Zone's grammar is at
// `@term/mill/code/zone`. What follows is the compiler's own parser and its
// `read.ts` bridge, bundled, so this file cannot drift from the language: it
// IS the language's parser.
//
// WHAT THIS REPLACED. 286 hand-written lines that split on spaces, tracked
// indent depth by hand and kept ONE `<...>` per line. A line carrying two
// values silently lost the first, so `time <made>, <toss>` parsed as a cache
// with no fetch time and read as stale the instant it was written.
//
// The shape returned:
//
//   head   the first word
//   term   the bare words after it, in order
//   code   the FIRST `<...>` value, empty when the line carries none
//   more   EVERY `<...>` value, in order
//   leaf   nested lines, from an indent or from a comma, in written order

"use strict";
var __read = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // code/read.ts
  var read_exports = {};
  __export(read_exports, {
    deepFormOf: () => deepFormOf,
    deepValueOf: () => deepValueOf,
    formOf: () => formOf,
    formsWith: () => formsWith,
    phraseOf: () => phraseOf,
    readTree: () => readTree,
    termOf: () => termOf,
    termsOf: () => termsOf,
    valueOf: () => valueOf
  });

  // ../make/code/parser/diagnostic.ts
  var CATALOG = {
    "syntax-error": {
      code: 1,
      message: "error in the structure of the tree",
      severity: "error",
      fix: "check the brackets, the two-space indentation, and the commas on this line"
    },
    "invalid-nesting": {
      code: 2,
      message: "the tree has invalid nesting",
      severity: "error",
      fix: "a number is a value: it cannot have children or be the head of a line"
    },
    "invalid-indentation": {
      code: 3,
      message: "the tree has invalid indentation",
      severity: "error",
      fix: "indent exactly one level (two spaces) deeper than the parent line"
    },
    "not-implemented": {
      code: 4,
      message: "this feature is not implemented yet",
      severity: "error",
      fix: "this construct is recognized but not yet compiled"
    },
    "unknown-name": {
      code: 5,
      message: "this name is not defined",
      severity: "error",
      fix: "define it, import it, or check the spelling"
    },
    "unexpected-node": {
      code: 6,
      message: "this node is not valid here",
      severity: "error",
      fix: "this term is not allowed in this position"
    },
    "type-mismatch": {
      code: 7,
      message: "the types do not match",
      severity: "error",
      fix: "make the value match the expected type, or adjust the annotation"
    },
    unproven: {
      code: 8,
      message: "this hold could not be proven",
      severity: "error",
      fix: "add the assumption it needs (e.g. a natural-number bound), or weaken the claim"
    },
    "incomplete-instance": {
      code: 9,
      message: "this trait implementation is missing methods",
      severity: "error",
      fix: "implement every method the trait declares"
    },
    // a `like <name>` naming no form, enum, primitive, generic, mask, alias or opaque native type: it used to compile
    // clean and emit a type the target language has never heard of
    "unknown-type": {
      code: 20,
      message: "this type name is not defined",
      severity: "warning",
      fix: "declare the form, import it, or check the spelling"
    },
    "unused-binding": {
      code: 10,
      message: "this binding is never used",
      severity: "warning",
      fix: "remove it, or use it"
    },
    "non-exhaustive": {
      code: 11,
      message: "this match does not cover every case",
      severity: "error",
      fix: "add the missing cases, or add an `else` branch"
    },
    "no-instance": {
      code: 12,
      message: "no trait instance for this type",
      severity: "error",
      fix: "implement the trait for this type with `wear` or `suit`"
    },
    "non-positive": {
      code: 13,
      message: "this type occurs in a non-positive position in its own definition",
      severity: "error",
      fix: "a type cannot appear to the left of an arrow within its own fields; restructure the definition"
    },
    "non-terminating": {
      code: 14,
      message: "this recursion could not be shown to terminate",
      severity: "warning",
      fix: "make a recursive call decrease an argument (e.g. a structurally smaller value), or add a base case"
    },
    // NOT PROVEN IS NOT PROVEN. This was a warning until 2026-09-18, which meant a claim the prover could not
    // reach compiled green: `a * b == a * a` over two naturals, and `secret a == a` where `secret` adds one, both
    // passed with nothing but a warning (tmp probe, law-proof-gate-0002). A claim nobody checked and a claim
    // somebody checked are not the same thing, and a gate that cannot tell them apart is not a gate. The stdlib
    // emitted zero of these across 534 files, so the change costs nothing and closes the hole.
    "unchecked-hold": {
      code: 15,
      message: "this hold is outside the decidable linear fragment and was not proven",
      severity: "error",
      fix: "rewrite it as a linear comparison (<, <=, >, >=, ==), prove it in the dependent kernel with `calm` / `fold` / `cite`, or mark the claim `mark open` to leave it open and counted"
    },
    "duplicate-instance": {
      code: 16,
      message: "this trait is implemented more than once for the same type",
      severity: "error",
      fix: "remove the overlapping implementation; a type may implement a trait only once (coherence)"
    },
    "duplicate-definition": {
      code: 19,
      message: "this name is defined more than once",
      severity: "error",
      fix: "rename one of the definitions; a top-level task or form name must be unique within the program"
    },
    "effect-error": {
      code: 17,
      message: "an effect is used inconsistently",
      severity: "error",
      fix: "mark the task async, await the asynchronous call, or only await asynchronous tasks"
    },
    "invalid-proof": {
      code: 18,
      message: "this proof does not establish the proposition",
      severity: "error",
      fix: "check the tactic and its argument; `melt` needs both sides to compute equal, `cite` needs a proven lemma of the same statement"
    },
    // A `rule` states a claim. A `task` of the same name fills it. Between the two the name is DECLARED and not
    // DEFINED, and nothing may use it as though it were proven. An unfilled claim used to compile silently, which
    // made a rule a comment with a type on it.
    "open-claim": {
      code: 21,
      message: "this claim has no proof",
      severity: "error",
      fix: "write a `task` of the same name whose body proves it, or mark the rule `mark open` to leave it open and counted"
    },
    // Using a claim that nobody has proven yet. The claim is a promise, and code that runs cannot be built on one.
    "open-claim-used": {
      code: 22,
      message: "this name is an open claim, not a proven one",
      severity: "error",
      fix: "prove it with a `task` of the same name, or stop calling it"
    },
    // A proof is a task, and a task the kernel never checked proves nothing. Until 2026-10-02 a claim was filled by
    // ANY task of its name: one that recursed forever proved `any x equals any y` with a warning (proof-by-default-0003),
    // and one whose type did not resolve proved a gradual nothing. A fill must be verified by the kernel, terminate,
    // and touch nothing outside itself, or it is not a proof.
    "unverified-proof": {
      code: 23,
      message: "this proof was not verified by the kernel",
      severity: "error",
      fix: "state the claim at types the kernel can read (load the forms it names), and write the proof in the pure fragment: no loops, no mutation, no native calls"
    },
    "looping-proof": {
      code: 24,
      message: "this proof is not shown to terminate",
      severity: "error",
      fix: "a proof that never ends proves anything, so recurse only on a structurally smaller argument"
    },
    "impure-proof": {
      code: 25,
      message: "this proof calls something impure",
      severity: "error",
      fix: "a proof may call only pure tasks: no native calls, no async, no writes through a record it did not make"
    },
    // A `twin` is another implementation of a task, which the compiler may choose in its place, so it must be able to
    // agree with it (note/term/optimize/admission.md). Each of these is a twin that could not.
    "twin-unknown": {
      code: 26,
      message: "this twin names no task",
      severity: "error",
      fix: "a twin is written `twin <task>, name <label>` beside a task this module can see"
    },
    "twin-of-impure": {
      code: 27,
      message: "this twin is of a task that is not pure",
      severity: "error",
      fix: "only a pure task can be computed another way: one that reaches native code, is async, or writes what it did not make has an order of effects a twin would have to repeat"
    },
    "twin-impure": {
      code: 28,
      message: "this twin is not pure",
      severity: "error",
      fix: "a twin of a pure task must be pure itself, or say `mark trust` to be admitted as trusted"
    },
    "twin-signature": {
      code: 29,
      message: "this twin's parameters are not its task's",
      severity: "error",
      fix: "name the task's parameters, in the task's order, with no types: a twin takes them from its task"
    },
    "twin-loops": {
      code: 30,
      message: "this twin is not shown to end where its task is",
      severity: "error",
      fix: "a twin that loops where its task returns is a wrong answer, not a faster one"
    },
    "twin-cycle": {
      code: 31,
      message: "these twins call each other in a cycle",
      severity: "error",
      fix: "break the cycle: a twin of one task may call another task, but not one whose twin calls back"
    },
    "guard-impure": {
      code: 32,
      message: "this twin's run-time check is not pure",
      severity: "error",
      fix: "a `hook test` decides which implementation runs, so it may not change anything or call native code"
    },
    "twin-choice": {
      code: 34,
      message: "this choice of implementation cannot be made",
      severity: "error",
      fix: "choose a twin the task has, eligible on this target, whose conditions the selection pass can honor"
    },
    "ease-unknown": {
      code: 33,
      message: "this relaxation is not one Term defines",
      severity: "error",
      fix: "the relaxations are `float-order` and `float-fused` (note/term/optimize/words.md)"
    },
    // A supervision tree OTP would start and then misbehave: a `transient` worker restarts only when it raises, so one
    // whose work can raise nothing never restarts, and is a `temporary` under a misleading name (check/supervise.ts)
    "dead-restart": {
      code: 35,
      message: "this transient worker can never restart",
      severity: "error",
      fix: "make it `temporary` if it is meant to run once, or let its work raise the failure it should restart on"
    },
    // `mark private` on a task makes it visible only inside the file that defines it. Until 2026-10-02 the mark was
    // read and nothing held anyone to it: names are package-global, so another file could call the task, or `find`
    // it in a `load`, and the output exported it (check/private.ts).
    "private-name": {
      code: 36,
      message: "this name is private to another file",
      severity: "error",
      fix: "remove `mark private` from the definition, or use it only from the file that defines it"
    },
    // `note private` is the old spelling. Still honored, so code written before the change keeps building.
    "note-private": {
      code: 37,
      message: "`note private` is the old spelling of `mark private`",
      severity: "warning",
      fix: "write `mark private`: privacy is a mark the compiler enforces, and a `note` is documentation"
    },
    // a call to an async task OUTSIDE every task (a top-level `host`, a component's body, a closure in either that is
    // not async), where nothing can wait for it: it hands back a pending value. `tick` says that is meant. Behind
    // the await switch (check/effects.ts, `setAwaitOutsideTasks`). note/term/plan/await-by-default-and-mark-metadata.md
    "async-outside-task": {
      code: 39,
      message: "a call to an async task outside any task, where nothing waits for it",
      severity: "error",
      fix: "move the call into a task, or write `tick` before it to start it without waiting"
    },
    // `note async`, `note unsafe`, `note draft` ...: metadata is `mark` since 2026-10-02, and `note <word>` is the
    // old spelling. Still read the same (the mill mints both as one form), so code written before keeps building.
    // note/term/plan/await-by-default-and-mark-metadata.md, section 4
    "note-metadata": {
      code: 38,
      message: "`note` is the old spelling of metadata, which is `mark`",
      severity: "warning",
      fix: "write `mark` for the `note`: `term lint --fix` rewrites it, and `note` is left for documentation"
    }
  };
  function diagnose(name, input) {
    const entry = CATALOG[name];
    return {
      code: entry.code,
      name,
      message: input.message ?? entry.message,
      file: input.file,
      span: input.span,
      markers: input.markers ?? [{ span: input.span }],
      // a specific hint if given, otherwise the catalog's default fix, so every diagnostic suggests a remedy
      hint: input.hint ?? entry.fix,
      severity: entry.severity
    };
  }

  // ../make/code/parser/token.ts
  var INTERPOLATION_MATCHERS = [
    "close-brace" /* CloseBrace */,
    "close-paren" /* CloseParen */,
    "close-angle" /* CloseAngle */,
    "comma" /* Comma */,
    "comment" /* Comment */,
    "decimal" /* Decimal */,
    "radix" /* Radix */,
    "newline" /* Newline */,
    "open-brace" /* OpenBrace */,
    "open-paren" /* OpenParen */,
    "open-angle" /* OpenAngle */,
    "name" /* Name */,
    "integer" /* Integer */,
    "space" /* Space */
  ];
  var TEXT_MATCHERS = [
    "open-brace" /* OpenBrace */,
    "close-angle" /* CloseAngle */,
    "chunk" /* Chunk */
  ];
  var NAME_MATCHERS = ["open-brace" /* OpenBrace */, "name" /* Name */];
  var DEFAULT_MATCHERS = [
    "close-brace" /* CloseBrace */,
    "close-paren" /* CloseParen */,
    "close-angle" /* CloseAngle */,
    "comma" /* Comma */,
    "comment" /* Comment */,
    "decimal" /* Decimal */,
    "radix" /* Radix */,
    "newline" /* Newline */,
    "open-brace" /* OpenBrace */,
    "open-paren" /* OpenParen */,
    "open-angle" /* OpenAngle */,
    "integer" /* Integer */,
    "space" /* Space */,
    "name" /* Name */
  ];
  var MODE_MATCHERS = {
    ["default" /* Default */]: DEFAULT_MATCHERS,
    ["text" /* Text */]: TEXT_MATCHERS,
    ["interpolation" /* Interpolation */]: INTERPOLATION_MATCHERS,
    ["name" /* Name */]: NAME_MATCHERS
  };
  var PATTERN = {
    ["close-brace" /* CloseBrace */]: /\}+/y,
    ["close-paren" /* CloseParen */]: /\)/y,
    ["close-angle" /* CloseAngle */]: />/y,
    ["comma" /* Comma */]: /, */y,
    ["comment" /* Comment */]: /#(?: +[^\n]+)?/y,
    ["decimal" /* Decimal */]: /-?\d+\.\d+/y,
    ["radix" /* Radix */]: /0[xXbBoOuU]\w+/y,
    ["newline" /* Newline */]: /\n/y,
    // a `{` opens an interpolation ONLY when an identifier follows (`{name}`); otherwise it is a literal brace. This lets
    // a text string carry JSON (`<{"a":1}>`) or a regex quantifier (`<[0-9]{3}>`) without escaping, while `{name}`
    // template / string interpolation still works.
    // A DOUBLE brace may be followed by whitespace, including a newline, before its content: `{{ foo }}` and a
    // `{{` that opens at the end of a line are interpolations holding a tree, which is what
    // test/parser/file/text-multiline.tree and sink.tree are written in. A SINGLE `{` still has to be followed
    // immediately by a letter, because that is what keeps an embedded JS or Rust block literal — `text <... { if
    // (sc === 0) ... }>` in decimal.tree would otherwise open an interpolation. Only the braces are captured, so
    // the interpolation's depth is still the length of the match.
    ["open-brace" /* OpenBrace */]: /\{+(?=\s*(?:[a-zA-Z_]|$))/y,
    ["open-paren" /* OpenParen */]: /\(/y,
    ["open-angle" /* OpenAngle */]: /</y,
    ["space" /* Space */]: / +/y,
    // A bare name may carry ESCAPED BRACES. `{` normally opens an interpolation, so a
    // glob written bare (`@/book/**/\{code,view\}/**/*.tree`) escapes them. The escaped
    // group is consumed WHOLE, commas included, since a comma would otherwise end the
    // token and split the pattern in two. `\{` / `\}` on their own are also literal.
    // The reader unescapes, so the value comes back as `{code,view}`.
    ["name" /* Name */]: /(?:\\\{[^\\]*\\\}|\\[{}<>\\]|[@~$%^&*'":.a-z0-9A-Z_\-?/])+/y,
    // a bare run of digits is an Integer, BUT digits followed by a hyphen and a letter (`24-cell`) is a kebab IDENTIFIER,
    // not a number, so the Integer matcher declines there and the Name matcher claims the whole `24-cell`. A pure number
    // (`24`, `24-3`) is unaffected.
    // a bare run of digits, OR a run written with THOUSAND SEPARATORS (`2,440,588`). The separated form requires exactly
    // three digits after each comma and no space, so an ordinary argument list (`take a, 3`) still splits on its comma:
    // only `1,234` binds as one number, never `1, 234`. The separated alternative is tried first, since the plain one
    // would otherwise match just the leading `2`.
    ["integer" /* Integer */]: /-?\d{1,3}(?:,\d{3})+(?![\d,])|-?\d+(?=\b)(?!-[a-zA-Z])/y,
    // a chunk runs over literal text, including a `{` that does not open an interpolation (not followed by an
    // identifier) and any `}`; it stops at `>` (close), `\` (escape), or an interpolation-opening `{`. Escapes cover
    // the delimiters (`\<` `\>` `\{` `\}`) and the standard characters (`\n` `\r` `\t` `\\`); the mill unescapes.
    // a backslash that does not introduce a known escape is a LITERAL backslash, so a Windows path (`text <\Temp>`) or
    // any other stray `\` can be written without doubling it. Without this the chunk matcher stops dead at the `\` and
    // no matcher can consume it, which surfaces as a structure error rather than anything about the backslash.
    // a run of braces followed by a letter opens an interpolation whole (`{x}` is depth one, `{{x}}` depth two, the
    // runtime interpolation), so the chunk matcher stops before a brace run that a letter follows
    ["chunk" /* Chunk */]: (
      // `e` alongside `nrt`: `\e` is the escape character (0x1B), which is what every ANSI colour sequence opens
      // with and the one thing a Term program needed to write terminal output without an npm package.
      /(?:\\[<>{}nrte\\]|\\(?![<>{}nrte\\])|\{+(?!\s*(?:[a-zA-Z_{]|$))|[^>{\\])+/y
    )
  };
  function tokenize(source) {
    const tokens = {
      file: source.file,
      text: source.text,
      lines: source.text.split("\n")
    };
    const braceStack = [];
    const found = [];
    const modeStack = ["default" /* Default */];
    const textOpenStack = [];
    const textDepthStack = [];
    let line = 0;
    let column = 0;
    let previous;
    function append(token) {
      if (!tokens.head) {
        tokens.head = token;
      } else if (previous) {
        token.previous = previous;
        previous.next = token;
      }
    }
    for (const rawLine of tokens.lines) {
      const lineText = `${rawLine}
`;
      let pos = 0;
      while (pos < lineText.length) {
        const mode = modeStack[modeStack.length - 1] ?? "default" /* Default */;
        if (mode === "text" /* Text */ && lineText.startsWith("\\", pos) && (lineText.startsWith("<", pos + 1) || lineText.startsWith(">", pos + 1))) {
          const token = {
            kind: "chunk" /* Chunk */,
            span: {
              start: { line, column },
              end: { line, column: column + 2 }
            },
            text: lineText[pos + 1]
          };
          append(token);
          previous = token;
          pos += 2;
          column += 2;
          continue;
        }
        if (mode === "text" /* Text */ && lineText.startsWith(">", pos) && (textDepthStack[textDepthStack.length - 1] ?? 0) > 0) {
          const token = {
            kind: "chunk" /* Chunk */,
            span: {
              start: { line, column },
              end: { line, column: column + 1 }
            },
            text: ">"
          };
          append(token);
          previous = token;
          pos += 1;
          column += 1;
          textDepthStack[textDepthStack.length - 1] -= 1;
          continue;
        }
        let matched = false;
        for (const kind of MODE_MATCHERS[mode]) {
          const pattern = PATTERN[kind];
          pattern.lastIndex = pos;
          const hit = pattern.exec(lineText);
          if (!hit) {
            continue;
          }
          matched = true;
          let size = hit[0].length;
          let text = lineText.slice(pos, pos + size);
          if (kind === "close-brace" /* CloseBrace */) {
            const open = braceStack[braceStack.length - 1];
            if (open) {
              size = open.length;
              text = text.slice(0, open.length);
            }
          }
          const token = {
            kind,
            span: {
              start: { line, column },
              end: { line, column: column + size }
            },
            text
          };
          append(token);
          previous = token;
          pos += size;
          column += size;
          if (kind === "open-brace" /* OpenBrace */) {
            braceStack.push(text);
          } else if (kind === "close-brace" /* CloseBrace */) {
            braceStack.pop();
          }
          switch (kind) {
            case "newline" /* Newline */:
              line++;
              column = 0;
              break;
            case "open-brace" /* OpenBrace */:
              modeStack.push("interpolation" /* Interpolation */);
              break;
            case "close-brace" /* CloseBrace */:
              modeStack.pop();
              break;
            case "open-angle" /* OpenAngle */:
              modeStack.push("text" /* Text */);
              textDepthStack.push(0);
              textOpenStack.push({ line, column });
              break;
            case "close-angle" /* CloseAngle */:
              modeStack.pop();
              textDepthStack.pop();
              textOpenStack.pop();
              break;
            // A comma is ORDINARY inside an interpolation. `{...}` and `{{...}}` hold a whole tree, not one name:
            // `{foo bar, baz}` and `{foo(bar,baz(bing boom))}` are both trees, read by the same rules as anywhere
            // else (a space nests, a comma pops one level). Space nesting already worked; the comma was refused,
            // which is what made `values.tree`'s `b{x y 123, 123}/c` and `index.tree`'s
            // `{another(a/b/c, 1, foo bar baz)}` unparseable even though both are fixtures of the grammar.
            //
            // The case that refusal was protecting against is a glob whose braces were never escaped
            // (`@/book/**/{code,view}/**`). That is still handled, one level up: an interpolation only OPENS on a
            // `{` followed by a name, so `{"a":1}` and `{ ... }` stay literal text, and a real `{code,view}` in a
            // path is written `\{code,view\}` as it always was. Checked across the tree: the only unescaped
            // `{name,` left is inside a `#` comment.
            case "chunk" /* Chunk */:
              if (mode === "text" /* Text */ && textDepthStack.length > 0) {
                textDepthStack[textDepthStack.length - 1] += (text.match(/(?<!\\)</g) ?? []).length;
              }
              break;
            default:
              break;
          }
          break;
        }
        if (!matched) {
          const bracedIndex = /\{(\d+)\}/y;
          bracedIndex.lastIndex = pos;
          const literalIndex = bracedIndex.exec(lineText);
          if (literalIndex) {
            found.push(
              diagnose("syntax-error", {
                file: source.file,
                span: {
                  start: { line, column },
                  end: { line, column: column + literalIndex[0].length }
                },
                message: `a literal index is a plain segment: write /${literalIndex[1]}, not /{${literalIndex[1]}}`,
                hint: "braces evaluate a name, `read x/{key}`; a number is a segment of its own"
              })
            );
            pos += literalIndex[0].length;
            column += literalIndex[0].length;
            continue;
          }
          found.push(
            diagnose("syntax-error", {
              file: source.file,
              span: previous ? previous.span : {
                start: { line, column },
                end: { line, column: column + 1 }
              }
            })
          );
          pos += 1;
          column += 1;
          continue;
        }
      }
      if (pos < lineText.length) {
        found.push(
          diagnose("syntax-error", {
            file: source.file,
            span: previous ? previous.span : {
              start: { line, column },
              end: { line, column: column + 1 }
            }
          })
        );
      }
    }
    if (textOpenStack.length > 0) {
      const at = textOpenStack[textOpenStack.length - 1];
      found.push(
        diagnose("syntax-error", {
          file: source.file,
          hint: "this text literal is never closed, so it swallows the rest of the file. Inside a literal `<` and `>` balance, so an unescaped one opens a bracket that never closes. Write `\\<` and `\\>` for literal angles",
          span: {
            start: { line: at.line, column: at.column },
            end: { line: at.line, column: at.column + 1 }
          }
        })
      );
    }
    if (found.length > 0) {
      return { ok: false, diagnostics: found };
    }
    return { ok: true, tokens };
  }

  // ../make/code/parser/event.ts
  var commaPopsOneLevel = true;
  var commaAfterLeafStays = true;
  function buildEvents(tokens) {
    const events = [];
    const contexts = [{ kind: "root" /* Root */ }];
    const indents = [
      { depth: 0, used: true, ownLine: true }
    ];
    const diagnostics = [];
    let atLineStart = true;
    let lastDepth = 0;
    let afterLeaf = "";
    const top = () => contexts[contexts.length - 1];
    const push = (frame) => contexts.push(frame);
    const pop = () => contexts.pop();
    const indent = () => indents[indents.length - 1];
    const pushIndent = (move = 0) => indents.push({ depth: lastDepth + move, used: true, ownLine: true });
    const popIndent = () => {
      if (indents.length > 1) {
        indents.pop();
      }
    };
    function fail(name2, token2, hint) {
      diagnostics.push(
        diagnose(name2, { file: tokens.file, span: token2.span, hint })
      );
    }
    let token = tokens.head;
    if (token) {
      do {
        const leafBefore = afterLeaf;
        afterLeaf = "";
        switch (token.kind) {
          case "open-brace" /* OpenBrace */:
            openInterpolation(token);
            break;
          case "close-brace" /* CloseBrace */:
            closeInterpolation();
            break;
          case "open-angle" /* OpenAngle */:
            atLineStart = false;
            openText(token);
            break;
          case "close-angle" /* CloseAngle */:
            closeText(token);
            afterLeaf = "literal";
            break;
          case "open-paren" /* OpenParen */:
            if (top()?.kind === "name" /* Name */) {
              pop();
              events.push({ kind: "close-name" /* CloseName */ });
            }
            push({ kind: "paren" /* Paren */, token });
            break;
          case "close-paren" /* CloseParen */:
            afterLeaf = closeParen() ? "call" : "";
            break;
          case "comma" /* Comma */:
            comma(leafBefore);
            break;
          case "comment" /* Comment */:
            atLineStart = false;
            events.push({ kind: "comment" /* Comment */, token });
            break;
          case "decimal" /* Decimal */:
            atLineStart = false;
            decimal(token);
            afterLeaf = "literal";
            break;
          case "radix" /* Radix */:
            atLineStart = false;
            radix(token);
            afterLeaf = "literal";
            break;
          case "space" /* Space */:
            space(token);
            afterLeaf = leafBefore;
            break;
          case "newline" /* Newline */:
            closeLine();
            atLineStart = true;
            break;
          case "chunk" /* Chunk */:
            atLineStart = false;
            chunk(token);
            break;
          case "name" /* Name */:
            atLineStart = false;
            name(token);
            break;
          case "integer" /* Integer */:
            atLineStart = false;
            integer(token);
            afterLeaf = "literal";
            break;
          default:
            break;
        }
      } while (token = token.next);
    }
    closeLine();
    if (diagnostics.length) {
      return { ok: false, diagnostics };
    }
    return { ok: true, stream: { ...tokens, events } };
    function startContent() {
      const frame = indent();
      if (atLineStart) {
        atLineStart = false;
        if (frame.ownLine !== false) {
          frame.ownLine = true;
        }
      } else if (!frame.used) {
        frame.ownLine = false;
      }
      frame.used = true;
    }
    function space(token2) {
      while (top()?.kind === "name" /* Name */) {
        events.push({ kind: "close-name" /* CloseName */ });
        pop();
      }
      if (atLineStart) {
        atLineStart = false;
        const frame = indent();
        let depth = Math.floor(token2.text.length / 2);
        if (token2.text.length % 2 !== 0) {
          fail(
            "invalid-nesting",
            token2,
            "indentation must be a multiple of two spaces"
          );
          depth = frame.depth + 1;
        } else if (depth > lastDepth + 1) {
          if (indents.length === 1) {
            fail(
              "invalid-indentation",
              token2,
              "indent one level deeper than the parent, not more"
            );
          }
          depth = lastDepth + 1;
        } else if (depth < frame.depth) {
          depth = frame.depth + 1;
        }
        let diff = depth - frame.depth;
        while (diff-- > 0) {
          contexts.push({ kind: "indent" /* Indent */ });
          events.push({ kind: "open-indent" /* OpenIndent */ });
        }
        lastDepth = depth;
      } else if (token2.previous?.kind === "integer" /* Integer */) {
        fail(
          "invalid-nesting",
          token2,
          "a number is a value, so nothing can nest after it on the same line"
        );
      }
    }
    function openText(token2) {
      pushIndent(1);
      push({ kind: "text" /* Text */ });
      events.push({ kind: "open-text" /* OpenText */, token: token2 });
      indent().ownLine = endsLineWithNewline(token2);
    }
    function endsLineWithNewline(token2) {
      if (token2.next?.kind === "chunk" /* Chunk */) {
        return Boolean(/^\s*\n$/.exec(token2.next.text));
      }
      return false;
    }
    function closeText(token2) {
      events.push({ kind: "close-text" /* CloseText */, token: token2 });
      pop();
      popIndent();
    }
    function decimal(token2) {
      startContent();
      events.push({
        kind: "decimal" /* Decimal */,
        token: token2,
        value: parseFloat(token2.text)
      });
    }
    function radix(token2) {
      startContent();
      const found = /^0([xXbBoOuU])([0-9a-fA-F]+)/.exec(token2.text);
      if (found) {
        const base = found[1].toLowerCase();
        const radixValue = base === "b" ? 2 : base === "o" ? 8 : 16;
        events.push({
          kind: "radix" /* Radix */,
          token: token2,
          value: parseInt(found[2], radixValue),
          radix: radixValue
        });
      } else {
        fail(
          "syntax-error",
          token2,
          "this looks like a based number but is malformed"
        );
      }
    }
    function chunk(token2) {
      const frame = indent();
      const startsLine = !token2.previous || token2.previous.span.end.line < token2.span.start.line;
      if (frame.ownLine) {
        token2.text = startsLine ? token2.text.slice(frame.depth * 2).trimEnd() : token2.text.trim();
      }
      const last = events[events.length - 1];
      if (last?.kind === "chunk" /* Chunk */ && frame.ownLine) {
        if (token2.text) {
          last.token.text = last.token.text ? last.token.text.endsWith("\n") ? `${last.token.text}${token2.text}` : `${last.token.text} ${token2.text}` : token2.text;
        } else if (token2.next?.kind === "chunk" /* Chunk */) {
          last.token.text += "\n\n";
        }
      } else {
        events.push({ kind: "chunk" /* Chunk */, token: token2 });
      }
    }
    function integer(token2) {
      startContent();
      events.push({
        kind: "integer" /* Integer */,
        token: token2,
        // thousand separators are presentation only: `2,440,588` is the number 2440588
        value: parseInt(token2.text.replace(/,/g, ""), 10)
      });
    }
    function comma(leafBefore) {
      if (top()?.kind === "name" /* Name */) {
        pop();
        events.push({ kind: "close-name" /* CloseName */ });
      }
      if (leafBefore === "call" && commaAfterLeafStays !== false || leafBefore === "literal" && commaAfterLeafStays === true) {
        return;
      }
      const closeOne = () => {
        if (top()?.kind !== "group" /* Group */) {
          return false;
        }
        const below = contexts[contexts.length - 2];
        if (!below || below.kind === "indent" /* Indent */ || below.kind === "root" /* Root */) {
          return false;
        }
        pop();
        events.push({ kind: "close-group" /* CloseGroup */ });
        return true;
      };
      if (commaPopsOneLevel) {
        closeOne();
        return;
      }
      while (closeOne()) {
      }
    }
    function name(token2) {
      openName(token2);
      if (token2.text.includes("/")) {
        const followsClose = token2.previous?.kind === "close-brace" /* CloseBrace */;
        const segments = token2.text.split("/");
        for (let i = 0; i < segments.length; i++) {
          const segment = segments[i];
          if (segment.startsWith("-") && !(i === 0 && followsClose)) {
            fail(
              "syntax-error",
              token2,
              "a path segment cannot start with a dash"
            );
            break;
          }
          const q = segment.indexOf("?");
          if (q !== -1 && q !== segment.length - 1) {
            fail(
              "syntax-error",
              token2,
              "the optional mark ? must be at the end of a segment"
            );
            break;
          }
        }
      }
      events.push({ kind: "chunk" /* Chunk */, token: token2 });
    }
    function openName(token2) {
      const previousKind = token2.previous?.kind;
      if (previousKind === void 0 || previousKind === "newline" /* Newline */ || previousKind === "comma" /* Comma */ || previousKind === "open-brace" /* OpenBrace */ || previousKind === "open-paren" /* OpenParen */ || previousKind === "space" /* Space */) {
        events.push({ kind: "open-group" /* OpenGroup */ });
        push({ kind: "group" /* Group */ });
        startContent();
        events.push({ kind: "open-name" /* OpenName */ });
        push({ kind: "name" /* Name */ });
      }
    }
    function openInterpolation(token2) {
      const previousKind = token2.previous?.kind;
      if (previousKind === void 0 || previousKind === "newline" /* Newline */ || previousKind === "space" /* Space */) {
        push({ kind: "group" /* Group */ });
        events.push({ kind: "open-group" /* OpenGroup */ });
        push({ kind: "name" /* Name */ });
        events.push({ kind: "open-name" /* OpenName */ });
      }
      push({ kind: "interpolation" /* Interpolation */, token: token2 });
      events.push({
        kind: "open-interpolation" /* OpenInterpolation */,
        token: token2,
        depth: token2.text.length
      });
      pushIndent(1);
    }
    function closeParen() {
      const owned = contexts.some((frame) => frame.kind === "paren" /* Paren */);
      walk: while (true) {
        switch (top()?.kind) {
          case "indent" /* Indent */:
            events.push({ kind: "close-indent" /* CloseIndent */ });
            pop();
            break;
          case "group" /* Group */:
            events.push({ kind: "close-group" /* CloseGroup */ });
            pop();
            break;
          case "name" /* Name */:
            events.push({ kind: "close-name" /* CloseName */ });
            pop();
            break;
          case "paren" /* Paren */:
            pop();
            break walk;
          default:
            break walk;
        }
      }
      if (owned && top()?.kind === "group" /* Group */) {
        events.push({ kind: "close-group" /* CloseGroup */ });
        pop();
        return true;
      }
      return false;
    }
    function closeInterpolation() {
      walk: while (true) {
        const frame = top();
        switch (frame?.kind) {
          case "name" /* Name */:
            events.push({ kind: "close-name" /* CloseName */ });
            pop();
            break;
          case "indent" /* Indent */:
            events.push({ kind: "close-indent" /* CloseIndent */ });
            pop();
            break;
          case "group" /* Group */:
            events.push({ kind: "close-group" /* CloseGroup */ });
            pop();
            break;
          case "interpolation" /* Interpolation */:
            events.push({
              kind: "close-interpolation" /* CloseInterpolation */,
              token: frame.token
            });
            pop();
            break walk;
          default:
            break walk;
        }
      }
      popIndent();
    }
    function closeLine() {
      walk: while (true) {
        switch (top()?.kind) {
          case "group" /* Group */:
            events.push({ kind: "close-group" /* CloseGroup */ });
            pop();
            break;
          case "indent" /* Indent */:
            events.push({ kind: "close-indent" /* CloseIndent */ });
            pop();
            break;
          case "name" /* Name */:
            events.push({ kind: "close-name" /* CloseName */ });
            pop();
            break;
          case "paren" /* Paren */: {
            const frame = top();
            pop();
            if (frame.token) {
              fail(
                "syntax-error",
                frame.token,
                "a parenthesis must be closed on the line it opens"
              );
            }
            break;
          }
          case "root" /* Root */:
            break walk;
          default:
            break walk;
        }
      }
    }
  }

  // ../make/code/parser/tree.ts
  function setParent(child, parent) {
    Object.defineProperty(child, "parent", {
      value: parent,
      enumerable: false,
      writable: true
    });
  }
  function buildTree(events, file, diagnostics) {
    const root = { kind: "root", nodes: [] };
    const stack = [{ line: [root], levels: [root], level: 0 }];
    const VOID_FRAME = { line: [], levels: [], level: 0 };
    const top = () => stack[stack.length - 1] ?? VOID_FRAME;
    const VOID_NODE = { kind: "void" };
    const base = () => top().line[top().line.length - 1] ?? VOID_NODE;
    const lift = (frame, node) => {
      if (frame.line.length === 2) {
        frame.levels.length = frame.level + 1;
        frame.levels.push(node);
      }
    };
    const unexpected = (event) => {
      const token = "token" in event ? event.token : void 0;
      diagnostics.push(
        diagnose("unexpected-node", {
          file,
          span: token ? token.span : zeroSpan(),
          message: `unexpected ${event.kind} here`
        })
      );
    };
    let pendingComments = [];
    for (const event of events) {
      switch (event.kind) {
        case "comment" /* Comment */:
          pendingComments.push({
            text: event.token.text,
            span: event.token.span
          });
          break;
        case "open-group" /* OpenGroup */: {
          const here = base();
          if (here.kind === "root" || here.kind === "group") {
            const group = { kind: "group", nodes: [] };
            if (pendingComments.length > 0) {
              group.comments = pendingComments;
              pendingComments = [];
            }
            here.nodes.push(group);
            setParent(group, here);
            top().line.push(group);
            lift(top(), group);
          } else if (here.kind === "interpolation") {
            const group = { kind: "group", nodes: [] };
            here.group = group;
            setParent(group, here);
            top().line.push(group);
            lift(top(), group);
          } else {
            unexpected(event);
          }
          break;
        }
        case "close-group" /* CloseGroup */:
        case "close-name" /* CloseName */:
        case "close-text" /* CloseText */: {
          const frame = stack[stack.length - 1];
          if (!frame) {
            unexpected(event);
            break;
          }
          frame.line.pop();
          break;
        }
        case "open-name" /* OpenName */: {
          const here = base();
          if (here.kind === "group") {
            const name = { kind: "name", parts: [] };
            here.nodes.push(name);
            setParent(name, here);
            top().line.push(name);
          } else {
            unexpected(event);
          }
          break;
        }
        case "open-text" /* OpenText */: {
          const here = base();
          if (here.kind === "group") {
            const text = { kind: "text", parts: [] };
            if (pendingComments.length > 0) {
              text.comments = pendingComments;
              pendingComments = [];
            }
            here.nodes.push(text);
            setParent(text, here);
            top().line.push(text);
          } else {
            unexpected(event);
          }
          break;
        }
        case "open-interpolation" /* OpenInterpolation */: {
          const here = base();
          if (here.kind === "name" || here.kind === "text") {
            const interpolation = {
              kind: "interpolation",
              depth: event.depth
            };
            here.parts.push(interpolation);
            setParent(interpolation, here);
            stack.push({
              line: [interpolation],
              levels: [interpolation],
              level: 0
            });
          } else {
            unexpected(event);
          }
          break;
        }
        case "close-interpolation" /* CloseInterpolation */:
          stack.pop();
          break;
        case "chunk" /* Chunk */: {
          const here = base();
          if (here.kind === "name") {
            const text = event.token.text;
            const optional = text.includes("?");
            const chunk = {
              kind: "chunk",
              text: optional ? text.replace(/\?/g, "") : text,
              token: event.token
            };
            here.parts.push(chunk);
            setParent(chunk, here);
            if (optional && here.parent) {
              here.parent.optional = true;
            }
          } else if (here.kind === "text") {
            const chunk = {
              kind: "chunk",
              text: event.token.text,
              token: event.token
            };
            here.parts.push(chunk);
            setParent(chunk, here);
          } else {
            unexpected(event);
          }
          break;
        }
        case "integer" /* Integer */: {
          const here = base();
          if (here.kind === "group") {
            const node = {
              kind: "integer",
              value: event.value,
              token: event.token
            };
            if (pendingComments.length > 0) {
              node.comments = pendingComments;
              pendingComments = [];
            }
            here.nodes.push(node);
            setParent(node, here);
          } else if (here.kind === "root") {
            diagnostics.push(
              diagnose("invalid-nesting", {
                file,
                span: event.token.span,
                hint: "a bare number is a value, not a name, so it cannot be the head of a line"
              })
            );
          } else {
            unexpected(event);
          }
          break;
        }
        case "decimal" /* Decimal */: {
          const here = base();
          if (here.kind === "group") {
            const node = {
              kind: "decimal",
              value: event.value,
              token: event.token
            };
            if (pendingComments.length > 0) {
              node.comments = pendingComments;
              pendingComments = [];
            }
            here.nodes.push(node);
            setParent(node, here);
          } else if (here.kind === "root") {
            diagnostics.push(
              diagnose("invalid-nesting", {
                file,
                span: event.token.span,
                hint: "a bare number is a value, not a name, so it cannot be the head of a line"
              })
            );
          } else {
            unexpected(event);
          }
          break;
        }
        case "radix" /* Radix */: {
          const here = base();
          if (here.kind === "group") {
            const node = {
              kind: "radix",
              value: event.value,
              radix: event.radix,
              token: event.token
            };
            if (pendingComments.length > 0) {
              node.comments = pendingComments;
              pendingComments = [];
            }
            here.nodes.push(node);
            setParent(node, here);
          } else if (here.kind === "root") {
            diagnostics.push(
              diagnose("invalid-nesting", {
                file,
                span: event.token.span,
                hint: "a bare number is a value, not a name, so it cannot be the head of a line"
              })
            );
          } else {
            unexpected(event);
          }
          break;
        }
        case "open-indent" /* OpenIndent */: {
          const frame = top();
          frame.level++;
          frame.line = [frame.levels[frame.level]];
          break;
        }
        case "close-indent" /* CloseIndent */: {
          const frame = top();
          frame.level--;
          frame.line = [frame.levels[frame.level]];
          break;
        }
        default:
          break;
      }
    }
    return root;
  }
  function zeroSpan() {
    return { start: { line: 0, column: 0 }, end: { line: 0, column: 0 } };
  }
  function parse(source) {
    const tokenResult = tokenize(source);
    if (!tokenResult.ok) {
      return { ok: false, diagnostics: tokenResult.diagnostics };
    }
    const eventResult = buildEvents(tokenResult.tokens);
    if (!eventResult.ok) {
      return { ok: false, diagnostics: eventResult.diagnostics };
    }
    const diagnostics = [];
    const tree = buildTree(
      eventResult.stream.events,
      source.file,
      diagnostics
    );
    if (diagnostics.length) {
      return { ok: false, diagnostics };
    }
    return { ok: true, tree };
  }

  // code/read.ts
  function literal(node, source) {
    const extent = tokenExtent(node);
    if (!extent) {
      return node.parts.map((part) => part.kind === "chunk" ? part.text ?? "" : "").join("");
    }
    return unescape(source.slice(extent.start, extent.end));
  }
  function unescape(text) {
    return text.replace(/\\([<>{}\\])/g, "$1");
  }
  function tokenExtent(node) {
    let start;
    let end;
    const visit = (value) => {
      if (!value || typeof value !== "object") {
        return;
      }
      const record = value;
      const token = record["token"];
      if (token?.span) {
        if (!start || before(token.span.start, start)) {
          start = token.span.start;
        }
        if (!end || before(end, token.span.end)) {
          end = token.span.end;
        }
      }
      for (const key of ["parts", "nodes"]) {
        const list = record[key];
        if (Array.isArray(list)) {
          list.forEach(visit);
        }
      }
      visit(record["group"]);
    };
    visit(node);
    return start && end ? { start, end } : void 0;
  }
  function before(a, b) {
    return a.line !== b.line ? a.line < b.line : a.column < b.column;
  }
  var Source = class {
    lines;
    constructor(text) {
      this.lines = text.split("\n");
    }
    slice(start, end) {
      if (start.line === end.line) {
        return (this.lines[start.line] ?? "").slice(
          start.column,
          end.column
        );
      }
      const out = [
        (this.lines[start.line] ?? "").slice(start.column)
      ];
      for (let line = start.line + 1; line < end.line; line++) {
        out.push(this.lines[line] ?? "");
      }
      out.push((this.lines[end.line] ?? "").slice(0, end.column));
      return out.join("\n");
    }
  };
  function isTerm(group) {
    return group.nodes.length === 1 && group.nodes[0]?.kind === "name";
  }
  function toForm(group, source) {
    const first = group.nodes[0];
    if (first?.kind !== "name") {
      return void 0;
    }
    const form = {
      head: literal(first, source),
      terms: [],
      values: [],
      forms: []
    };
    for (const node of group.nodes.slice(1)) {
      readInto(form, node, source);
    }
    return form;
  }
  function readInto(form, node, source) {
    switch (node.kind) {
      case "text": {
        const text = literal(node, source);
        form.values.push(text);
        if (form.value === void 0) {
          form.value = text;
        }
        break;
      }
      case "name":
        form.terms.push(literal(node, source));
        break;
      case "integer":
      case "decimal":
      case "radix": {
        const text = String(node.value);
        form.values.push(text);
        if (form.value === void 0) {
          form.value = text;
        }
        break;
      }
      case "group": {
        if (isTerm(node)) {
          const only = node.nodes[0];
          if (only?.kind === "name") {
            form.terms.push(literal(only, source));
          }
          return;
        }
        const nested = toForm(node, source);
        if (nested) {
          form.forms.push(nested);
        }
        break;
      }
      default:
        break;
    }
  }
  function readTree(input) {
    const result = parse({ file: input.file, text: input.text });
    if (!result.ok) {
      return { ok: false, diagnostics: result.diagnostics };
    }
    return { ok: true, forms: formsOf(result.tree, new Source(input.text)) };
  }
  function formsOf(tree, source) {
    const out = [];
    for (const group of tree.nodes) {
      const form = toForm(group, source);
      if (form) {
        out.push(form);
      }
    }
    return out;
  }
  function formOf(form, head) {
    return form.forms.find((f) => f.head === head);
  }
  function formsWith(form, head) {
    return form.forms.filter((f) => f.head === head);
  }
  function valueOf(form, head) {
    return formOf(form, head)?.value;
  }
  function termOf(form, head) {
    return formOf(form, head)?.terms[0];
  }
  function deepFormOf(form, head) {
    for (const nested of form.forms) {
      if (nested.head === head) {
        return nested;
      }
      const found = deepFormOf(nested, head);
      if (found) {
        return found;
      }
    }
    return void 0;
  }
  function deepValueOf(form, head) {
    return deepFormOf(form, head)?.value;
  }
  function termsOf(form) {
    return form.terms.join(" ");
  }
  function phraseOf(form) {
    const words = [...form.terms];
    for (const nested of form.forms) {
      words.push(nested.head);
      const rest = phraseOf(nested);
      if (rest) {
        words.push(rest);
      }
    }
    return words.join(" ");
  }
  return __toCommonJS(read_exports);
})();


const mill = (() => {
  const toLeaf = (form: any): any => ({
    head: String(form.head ?? ''),
    term: (form.terms ?? []).map((one: any) => String(one)),
    code: form.value === undefined ? '' : String(form.value),
    more: (form.values ?? []).map((one: any) => String(one)),
    leaf: (form.forms ?? []).map(toLeaf),
  })

  return {
    read: (text: string): any[] => {
      const got = (__read as any).readTree({ file: 'zone.tree', text })

      if (!got.ok) {
        const first = got.diagnostics?.[0]

        process.stderr.write(
          'The declaration does not parse.\n\n  ' +
            String(first?.message ?? 'syntax error') +
            (first?.hint ? '\n\n  ' + first.hint : '') +
            '\n',
        )
        process.exit(1)
      }

      return got.forms.map(toLeaf)
    },

    // A stored secret's NOTE. A person's field first: it arrives from the
    // web vault with `\r\n` line endings, and it may be prose. So the
    // endings are normalised before the parse, and a note the parser
    // refuses yields NO leaves rather than an exit. `read` above is the
    // declaration, where a parse error is a bug in a file we own and
    // must stop the run. A note is not ours, and one unparseable note
    // must not take every `zone read` down, which it did once.
    note: (text: string): any[] => {
      const got = (__read as any).readTree({
        file: 'note.tree',
        text: String(text ?? '').replace(/\r\n?/g, '\n'),
      })

      return got.ok ? got.forms.map(toLeaf) : []
    },
  }
})()
